version: "3"
services:
    postgre:
        container_name: lin1000-postgresql
        ports:
            - '5432:5432'
        volumes:
            - '${DOCKER_COMPOSE_HOME}/postgreSQL/pgdata:/var/lib/postgresql/data'
        environment:
            - POSTGRES_PASSWORD=q1w2e3r4
        image: postgres
    rabbitmq:
        ports:
            - '5672:5672'
            - '15672:15672'
        container_name: lin1000-rabbitmq
        image: 'rabbitmq:3-management'        